Implementation for local server and client
SpongePowered/SpongeForge pull request #1445
Opened 2017-04-18 20:13 UTC by killjoy1221

[SpongeAPI](https://github.com/SpongePowered/SpongeAPI/pull/1540) | [SpongeForge](#)

Right now, `getClientPlayer()` will likely throw a class cast exception because `Player` is only mixined to `EntityPlayerMP` and not `AbstractClientPlayer` or its subclasses.

2017-04-18 22:57 UTC, kashike requested changes

2017-04-18 22:57 UTC, kashike commented on src/main/java/org/spongepowered/mod/mixin/core/client/MixinMinecraft.java
> +        return Optional.ofNullable((World) world);
`this.`

2017-04-18 22:57 UTC, kashike commented on src/main/java/org/spongepowered/mod/mixin/core/client/MixinMinecraft.java
> +        return Optional.ofNullable((ClientPlayer) player);
`this.`

2017-04-18 22:57 UTC, kashike commented on src/main/java/org/spongepowered/mod/mixin/core/client/MixinMinecraft.java
> +        return Optional.ofNullable((LocalServer) theIntegratedServer);
`this.`

2017-04-18 22:57 UTC, kashike commented on src/main/java/org/spongepowered/mod/mixin/core/client/server/MixinIntegratedServer.java
> +        this.shareToLAN(mc.playerController.getCurrentGameType(), false);
`this.`

2017-04-18 22:57 UTC, kashike commented on src/main/java/org/spongepowered/mod/mixin/core/client/MixinMinecraft.java
> +        return fileResourcepacks.toPath();
`this.`

2017-04-18 22:57 UTC, kashike commented on src/main/java/org/spongepowered/mod/mixin/core/client/MixinMinecraft.java
> +        return fileAssets.toPath();
`this.`

2017-04-18 22:57 UTC, kashike commented on src/main/java/org/spongepowered/mod/mixin/core/client/MixinMinecraft.java
> +                        ((TranslatableText) this.kickMessage).getTranslation().get(Locale.forLanguageTag(this.mcLanguageManager.getCurrentLanguage()
no need to reformat this

2017-04-18 22:57 UTC, kashike commented on src/main/java/org/spongepowered/mod/mixin/core/client/MixinMinecraft.java
> +                    + "client/LoadingScreenRenderer;displayLoadingString(Ljava/lang/String;)V", ordinal = 0))
no need to reformat this

2017-04-19 00:21 UTC, kashike requested changes

2017-04-19 00:21 UTC, kashike commented on src/main/java/org/spongepowered/mod/mixin/core/client/network/MixinNetHandlerPlayClient.java
> +public abstract class MixinNetHandlerPlayClient implements ServerConnection, TabList, IMixinNetPlayHandler {
I'd prefer a `ClientTabList` class that implements `TabList`

2017-04-19 18:39 UTC, Minecrell commented on src/main/java/org/spongepowered/mod/mixin/core/client/network/MixinNetHandlerPlayClient.java
> +    public void onHandleListHeaderFooter(SPacketPlayerListHeaderFooter packetIn, CallbackInfo ci) {
Can be private

2017-04-19 18:39 UTC, Minecrell commented on src/main/java/org/spongepowered/mod/mixin/core/client/network/MixinNetHandlerPlayClient.java
> +    public void onEntryAdded(SPacketPlayerListItem packetIn, CallbackInfo ci, Iterable iter, SPacketPlayerListItem.AddPlayerData
Can be private

2018-10-26 17:55 UTC, ImMorpheus commented
Superseded by https://github.com/SpongePowered/SpongeForge/pull/2096

See https://github.com/SpongePowered/SpongeAPI/pull/1540#issuecomment-417197528

2018-10-26 17:55 UTC, closed without merging