Implement Container.getPlugin() for Forge mods.
SpongePowered/SpongeForge pull request #1521
Opened 2017-05-17 13:58 UTC by JBYoshi

[SpongeCommon](https://github.com/SpongePowered/SpongeCommon/pull/1357) | **SpongeForge**

2017-05-24 01:38 UTC, kashike requested changes

2017-05-24 01:38 UTC, kashike commented on src/main/java/org/spongepowered/mod/mixin/core/fml/common/registry/MixinNetworkRegistry.java
> +@Mixin(NetworkRegistry.class, remap=false)
`remap = false` (spacing)

2017-05-24 01:41 UTC, JBYoshi commented on src/main/java/org/spongepowered/mod/mixin/core/fml/common/registry/MixinNetworkRegistry.java
> +@Mixin(NetworkRegistry.class, remap=false)
...And the line I wrote doesn't even compile - I forgot `value =`. That's what I get for coding when I'm too pressed on time...

2017-05-24 01:42 UTC, JBYoshi commented on src/main/java/org/spongepowered/mod/mixin/core/fml/common/registry/MixinNetworkRegistry.java
> +@Mixin(NetworkRegistry.class, remap=false)
Fixed.

2017-08-13 23:48 UTC, JBYoshi commented
Closed in https://github.com/SpongePowered/SpongeForge/commit/e15410874c1dadc78a1a487e6f2d457fa31ab2d7.

2017-08-13 23:48 UTC, closed without merging