Add '/sponge mods' command
SpongePowered/SpongeForge pull request #1719
Opened 2017-08-13 20:00 UTC by Grinch

**[SpongeCommon](https://github.com/SpongePowered/SpongeCommon/pull/1481)** | **SpongeForge**

Based on @zachoooo's work from SpongeCommon #
 
- Filters out plugins
- Ensures Minecraft, MCP, FML, MinecraftForge, SpongeAPI and SpongeForge are first in the list (none of these are filtered from this list)

**Screenshot**
![](http://i.imgur.com/xO2y198.png)

Signed-off-by: Steven Downer <grinch@outlook.com>

2017-08-13 20:57 UTC, kashike commented on src/main/java/org/spongepowered/mod/command/SpongeForgeCommand.java
> +                        final List<String> listStatics = Lists.newArrayList("minecraft", "mcp", "FML", "forge",
Can be a constant.

2017-08-13 20:58 UTC, kashike requested changes

2017-08-13 20:58 UTC, kashike commented on src/main/java/org/spongepowered/mod/mixin/core/common/MixinSpongeImplHooks.java
> +     * @author
you!

2017-08-13 20:58 UTC, kashike commented on src/main/java/org/spongepowered/mod/mixin/core/common/MixinSpongeImplHooks.java
> +     * @author
you!

2017-08-13 20:58 UTC, kashike commented on src/main/java/org/spongepowered/mod/mixin/core/common/MixinSpongeImplHooks.java
> +     * @author
you!

2017-08-14 17:51 UTC, Zidane commented
Merged in https://github.com/SpongePowered/SpongeForge/commit/2c46e519e3f3583524f29947a1f2cfba74608d77

Thanks!

2017-08-14 17:51 UTC, closed without merging