Add support for jarinjar
SpongePowered/SpongeForge pull request #2252
Opened 2018-06-23 18:17 UTC by killjoy1221

SpongeForge (incoming) | [SpongeCommon](https://github.com/SpongePowered/SpongeCommon/pull/1955)

This adds mixin as a `ContainedDep` in the jar for Forge to load. It fixes issues where another mod loads an earlier version of mixin, which causes conflicts.

Currently waiting on MinecraftForge/MinecraftForge#4993

2018-06-24 01:09 UTC, kashike requested changes

2018-06-24 01:09 UTC, kashike commented on build.gradle
> +
extra line

2018-08-08 16:14 UTC, trender7 commented
cant wait :P

2019-06-06 04:09 UTC, Zidane commented
I am closing this until someone investigates the changes in 1.14 and the end result that will happen with the Mixin update.

2019-06-06 04:09 UTC, closed without merging